language: python
python:
  - "3.6"
  - "3.7"
cache: pip
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

install:
  - sudo pip3 install --pre scapy
  - sudo pip3 install -r requirements.txt

script: sudo ./test.sh
