language: python
python:
  - "3.6"
cache: pip
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "tcpdump"

install:
  - sudo pip3 install --upgrade setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip3 install --pre scapy
  - sudo pip3 install -r requirements.txt

script: sudo ./test.sh
