language: python
dist: trusty
python:
  - "3.6"
  - "3.7"

install:
  - sudo apt install -y tcpdump python3
  - sudo python3 -m pip install --pre scapy
  - sudo python3 -m pip install -r requirements.txt

script: sudo ./test.sh
