language: python
python:
  - "3.6"
cache: pip
addons:
  apt:
    update: true
    packages:
      - "python3.6"
      - "python3.6-pip"

install:
  - sudo pip3 install --pre scapy
  - sudo pip3 install -r requirements.txt

script: sudo ./test.sh
