language: python
python:
  - "3.6"
cache: pip
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

install:
  - sudo pip3.6 install --pre scapy
  - sudo pip3.6 install -r requirements.txt

script: sudo ./test.sh
